name: meuni_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Stacked
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  # API
  http: ^1.1.0

  # Firebase Auth
  auth_buttons: ^3.0.2
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  google_sign_in: ^6.1.6

  # UI
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/splash-screen.png