// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVeFYnP03K23cGsb5JguWr43Hy2X3acvk',
    appId: '1:807288899830:web:c24bb130aae6f4716dc4d7',
    messagingSenderId: '807288899830',
    projectId: 'meuni-9d616',
    authDomain: 'meuni-9d616.firebaseapp.com',
    databaseURL: 'https://meuni-9d616-default-rtdb.firebaseio.com',
    storageBucket: 'meuni-9d616.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyqaA7zfo3HeqjspDHMjZLBYJf7SY4y-Y',
    appId: '1:807288899830:android:5407e991c85f0d9c6dc4d7',
    messagingSenderId: '807288899830',
    projectId: 'meuni-9d616',
    databaseURL: 'https://meuni-9d616-default-rtdb.firebaseio.com',
    storageBucket: 'meuni-9d616.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1qna4rlGnwhIoX3bBBiGgZKIkHClR7Qg',
    appId: '1:807288899830:ios:9d21d04b2568fc576dc4d7',
    messagingSenderId: '807288899830',
    projectId: 'meuni-9d616',
    databaseURL: 'https://meuni-9d616-default-rtdb.firebaseio.com',
    storageBucket: 'meuni-9d616.appspot.com',
    androidClientId:
        '807288899830-0ma7ogp71k689hqss9eehl5si8u9m3er.apps.googleusercontent.com',
    iosClientId:
        '807288899830-kt46aglaenp4f4tlvk039j0kkv4cvdn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.meuniMobile',
  );
}
