include: package:lints/recommended.yaml

linter:
  rules:
    prefer_single_quotes: true
    directives_ordering: true
    prefer_relative_imports: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_lambdas: true
    unawaited_futures: true
    discarded_futures: true
