name: Flutter

defaults:
  run:
    working-directory: mobile

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      # Uses stable version of flutter
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test

      - name: Build Android apk
        run: flutter build apk

      - name: Build Android appbundle
        run: flutter build appbundle
